### ISSUE TITLE
Node v4.4.0

### ISSUE THREAD

**Issue by km-tr** [mattlewis92/bless-css-webpack-plugin#1]
Are there plans to correspond to Node v4.4.0?
Or may I correspond to Node v4.4.0 and issue a pull request?

**Comment by mattlewis92** [comment]
I personally develop on node 7 so it's not something I plan to add, however I'd happily accept a PR that adds node 4 support. There's only a bit of destructuring and default parameters in use so I'd prefer it if you just de-sugared it rather than using babel. Thanks! 😄

**Comment by km-tr** [comment]
#2
